### ISSUE TITLE
Check doc for technical clarity

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#23]
For the following document edits, https://github.com/tearust/tea-docs/commit/527dd1cae265a72df74cd4678e88634d9b373087#diff-1c810fbf6ad913217c08e36cf04fe47bc4e50896baf59b95421ed7d60fc2e364

Can you check for clarity? I've left comments at the areas I re-worded the most.

**Comment by kevingzhang** [comment]
added my comments, please take a look. If you have future questions, assign to me again

**Comment by geopor** [comment]
Responded to comments and made requested revisions.
