### ISSUE TITLE
Check folder before updating on website: What is TEA 

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#24]
The following document and all 17 linked files have been edited and should be looked over before uploading to the website server:
https://teaproject.org/#/doc_list/What_is_TEA%3F%2FREADME.md

**Comment by geopor** [comment]
https://github.com/tearust/tea-docs/commit/527dd1cae265a72df74cd4678e88634d9b373087#diff-1c810fbf6ad913217c08e36cf04fe47bc4e50896baf59b95421ed7d60fc2e364

Last section needs updating due to progress since it was written.

**Comment by geopor** [comment]
https://github.com/tearust/tea-docs/blob/main/What_is_TEA%3F/Token_economy.md

This document appears linked in 3 different places on the website: in the Readme, and twice on the sidebar. Would suggest removing 1 of the links from the sidebar.

<img width="1134" alt="Screen Shot 2021-07-21 at 9 43 42 AM" src="https://user-images.githubusercontent.com/86096370/126527958-40dba5d0-bd18-4991-adab-8e60166112b7.png">

**Comment by kevingzhang** [comment]
> https://github.com/tearust/tea-docs/blob/main/What_is_TEA%3F/Token_economy.md
> 
> This document appears linked in 3 different places on the website: in the Readme, and twice on the sidebar. Would suggest removing 1 of the links from the sidebar.
> 
> <img alt="Screen Shot 2021-07-21 at 9 43 42 AM" width="1134" src="https://user-images.githubusercontent.com/86096370/126527958-40dba5d0-bd18-4991-adab-8e60166112b7.png">

Yes please do.

In the future, please create 3 separate issues rather than put them into one.

**Comment by kevingzhang** [comment]
what you can do is to remove the Token economy link under What is TEA?

**Comment by geopor** [comment]
Ok done:
https://github.com/tearust/tea-docs/commit/0dae1ccc0e11f13863f59f94c017fa74f34bd120
