### ISSUE TITLE
do you think this part is still helpful, if not, you can remove it

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-docs#25]
![image](https://user-images.githubusercontent.com/1761809/126565934-2edfbc39-bbec-4a0b-9885-9a713967b0b8.png)

**Comment by geopor** [comment]
I moved it to a better section, the intro to the blog section. Also changed it to 3rd person ("Kevin wrote ..") to make it seem more professional.
https://github.com/tearust/tea-docs/commit/c833c57bedd6ae955261821d776583bd476de80a
