### ISSUE TITLE
there are Under construction page, we should either fill content in or remove the link

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-docs#26]
We still have some links to page "under construction", such as What is TEA?/Key Concepts, Use Cases. 
I would suggest we fill in the content (I know you will ) or remove the links

**Comment by geopor** [comment]
https://github.com/tearust/tea-docs/commit/aca63519064e051158d50c9e9d632afbaa7bcb54
- Added a couple links to *Use Cases*, let me know if there are other use cases you want me to add.
- Made *Repin* into a canonical document. Each document in the future referencing repinning can embed Under_the_hood/Repin.md

- Made *Delegation Chain* to be an embeddable document. Embedded it in Under_the_hood/README.md.

https://github.com/tearust/tea-docs/commit/d6fb0f016596d2343a92c40a79a8f1555cd7f91c
- Left the following empty files where they are in the directory in case we want to go back and work on them, and removed them from the sidebar:

What_is_Tea/
- Key Concepts

Under_the_hood/
- Revenue_distribution
- Select_an_executor
- Submit_task

**Comment by kevingzhang** [comment]
Before assign it back to me, make sure that you have asked Jacky to refresh the website. Once you can see it take effect on the website (not your local machine), you can assign to me to verify then close

**Comment by geopor** [comment]
@liyangwood can you refresh the website so we can see the changes

**Comment by kevingzhang** [comment]
I think this is done so I close it
