### ISSUE TITLE
Once you complete the tutorial of preview 1, please replace the current "Try the demo"

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-docs#27]
The current "Try the demo" is for Nov 2020 demo. We can move it to a separated folder (you can decide where to put, no need to remove, just no longer highlighted).
Instead, the "try the demo" because our new Preview 1 demo.

**Comment by geopor** [comment]
Docs moved to Demo_2020_Nov-Archived/ folder unlinked from sidebar, new updated documentation in their place on sidebar https://github.com/tearust/tea-docs/commit/de0256fddd2455d318f921b92cf554aaf9fb28b5
