### ISSUE TITLE
the left index column need to be consistent. 

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-docs#29]
![image](https://user-images.githubusercontent.com/1761809/126813190-2b23bdac-fa0c-4e1e-b206-049b3184efb6.png)

We can change all "Section1" to its real title "Introduction", "Section3 Solution" =>"Solution"

change in the config.yaml and also the file name.

Your change won't be shown on the cloud website direction, but you can see it in your local machine website

**Comment by geopor** [comment]
Done https://github.com/tearust/tea-docs/commit/08eb7358fd83dedadb0699108f2f8ec9d7adff0a
