### ISSUE TITLE
we also need to update the website's whitepaper page.

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-docs#30]
![image](https://user-images.githubusercontent.com/1761809/126813524-89eec46b-4822-4a88-b31e-9236e821c2d6.png)
This cannot be done by modifying the tea-docs repo, please write change request issue and send to Jacky.

**Comment by geopor** [comment]
Do you want this page to look like this:

<h4>TEA Project Technical White Paper</h4>

Legal Disclaimer
Introduction
Problem Statement
Our Solution
TEA Components
Tokenomics
Product Roadmap
Appendix A
Appendix B
Bibliography

<h4>PDF Versions</h4>
English (PDF)
Chinese (Coming soon)

**Comment by kevingzhang** [comment]
we no longer need the TEA Project Technical White Paper and Economy White Paper. but I am ok to leave the Pitch deck there.

**Comment by geopor** [comment]
<h4>TEA Project Technical White Paper</h4>

Legal Disclaimer
Introduction
Problem Statement
Our Solution
TEA Components
Tokenomics
Product Roadmap
Appendix A
Appendix B
Bibliography

<h4>Pitch deck</h4>

English (PDF)

Chinese 中文 (Coming soon)

**Comment by kevingzhang** [comment]
@liyangwood do you have any question on this issue? if you do not, please update the white paper page.

**Comment by liyangwood** [comment]
done

**Comment by geopor** [comment]
Hi @liyangwood the header of the website as well as this page has "White Paper", it should read "Whitepaper" (one word)

Also to keep capitalization consistent, "Pitch deck" should be "Pitch Deck".

![Screen Shot 2021-07-26 at 9 21 28 PM](https://user-images.githubusercontent.com/86096370/127095274-8d954246-083e-41d6-932d-7a0ce7547e64.png)

**Comment by liyangwood** [comment]
fixed
