### ISSUE TITLE
I found all biweekly report not showing in the website, that is because you did not update the config.yaml

### ISSUE THREAD

**Issue by kevingzhang** [tearust/tea-docs#32]

**Comment by kevingzhang** [comment]
Please update the config.yml. let me know and I will update the website

**Comment by geopor** [comment]
Done: https://github.com/tearust/tea-docs/commit/24a29e7c0bf1a5c0b8f9423b8074268440816bdf

**Comment by kevingzhang** [comment]
updated server, they are shown in teaproejct.org now
