### ISSUE TITLE
Homepage edit: footer links

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#34]
Please add the following two links to the footer as shown in the screenshot:

<img width="1246" alt="Screen Shot 2021-11-09 at 11 00 05 AM" src="https://user-images.githubusercontent.com/86096370/140987698-3fc6f472-ec3b-4ef2-aa78-45a674d78cb7.png">

- Telegram -  https://t.me/teaprojectorg
- Twitter - https://twitter.com/teaprojectorg

**Comment by liyangwood** [comment]
Done
