### ISSUE TITLE
Timeout gracefully when resource isn't found

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#35]
On website, especially in the documents section, if you follow a link that has changed and isn't pointing to anything what happens is that the **Loading** message will spin forever. With other content management systems, fairly quickly it will give at least a 404 back so the user isn't waiting forever

**Comment by geopor** [comment]
This is still an issue:

<img width="835" alt="Screen Shot 2021-11-16 at 9 42 37 AM" src="https://user-images.githubusercontent.com/86096370/142046089-dc9c8ff7-3b29-4d4d-9da8-0f25bf8bd623.png">

**Comment by liyangwood** [comment]
Outdated
