### ISSUE TITLE
Change link for Pitch Deck

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#37]
In the header of the homepage, the pitch deck link will need to be updated:

<img width="1179" alt="Screen Shot 2022-03-15 at 2 52 42 PM" src="https://user-images.githubusercontent.com/86096370/158478927-622fe0c5-1253-40b3-9361-55de69d56af8.png">

to this link:

https://github.com/tearust/tea-docs/blob/main/pdf/TEA_Project_Pitch%20Deck_Mar_2022.pdf

**Comment by liyangwood** [comment]
Done

**Comment by kevingzhang** [comment]
@liyangwood Are you sure you done? I did not see your code chnage commit, and the website did not show the latest link.
 Please verify yourself before assigning issue to others.

**Comment by liyangwood** [comment]
it can closed
