### ISSUE TITLE
Updated litepaper and white paper

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#38]
@kevingzhang here are the updated litepaper: https://github.com/tearust/tea-docs/blob/main/Whitepaper_v2/_Litepaper.md

And the most recent edits to white paper:

https://github.com/tearust/tea-docs/commit/b7cf04e127bcd891ffcdff0eedbc3a4d5e6061e8
https://github.com/tearust/tea-docs/commit/a23e74b62c7bcfe77c22684520537b0bca009e44

After making sure everything looks ok, please assign to @liyangwood to push new versions to website:

- https://github.com/tearust/tea-docs/blob/main/pdf/tea-project-litepaper-2022.2.pdf
- https://github.com/tearust/tea-docs/blob/main/pdf/tea-project-whitepaper-2022.2.pdf

**Comment by geopor** [comment]
A couple questions-

This doesn't seem correct:

> Camellia mining gives miners a chance to earn block rewards from performing routine tasks such as running remote attestation of computing nodes, proposing new blocks, and running smart contracts.

Also, are we doing away with Genesis loans now that we'll have at least an AMM for potential miners to buy TEA directly?

**Comment by kevingzhang** [comment]
The content is good enough.
 1.I would suggest to have links to some other resources online. I am not sure if it spopular in lite paper or white paper. If not, you can ignore my comment on this.

 2. Some reference. In most white paper , they will list the reference at the end of article. We probably should do that too. Using the reference can consolidate our opinion. Especially those paper that we use as evidence. For example, the Italian scientist research on GPS on Rpi on the Applied 
Science. 

3. We can publish and keep the paper updated all the time. Just make sure you always have a version number somewhere in the document. We should update them every few months. So make a version helps.

4. Please make quick update and publish to website. Our current webiste documents are out dated for a while.

**Comment by kevingzhang** [comment]
Once down, create another issue and ask Jacky to update website
