### ISSUE TITLE
Update website: new links for litepaper + white paper + pitch deck

### ISSUE THREAD

**Issue by geopor** [tearust/tea-docs#39]
@liyangwood please update the website header links for litepaper / whitepaper / pitch deck to the following pdfs:

- https://github.com/tearust/tea-docs/blob/main/pdf/tea-project-litepaper-2022.2.pdf
- https://github.com/tearust/tea-docs/blob/main/pdf/tea-project-whitepaper-2022.2.pdf
- https://github.com/tearust/tea-docs/blob/main/pdf/TEA-Project-Pitch-Deck-v5.1.pdf

**Comment by liyangwood** [comment]
Donee
